// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiBoxOffice imdbapi box office
//
// swagger:model imdbapiBoxOffice
type ImdbapiBoxOffice struct {

	// The domestic box office gross for the movie.
	DomesticGross *ImdbapiMoney `json:"domesticGross,omitempty"`

	// The opening weekend box office gross for the movie.
	OpeningWeekendGross *ImdbapiOpeningWeekendGross `json:"openingWeekendGross,omitempty"`

	// The production budget for the movie.
	ProductionBudget *ImdbapiMoney `json:"productionBudget,omitempty"`

	// The total worldwide box office gross for the movie.
	WorldwideGross *ImdbapiMoney `json:"worldwideGross,omitempty"`
}

// Validate validates this imdbapi box office
func (m *ImdbapiBoxOffice) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDomesticGross(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOpeningWeekendGross(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProductionBudget(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWorldwideGross(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiBoxOffice) validateDomesticGross(formats strfmt.Registry) error {
	if swag.IsZero(m.DomesticGross) { // not required
		return nil
	}

	if m.DomesticGross != nil {
		if err := m.DomesticGross.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("domesticGross")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("domesticGross")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiBoxOffice) validateOpeningWeekendGross(formats strfmt.Registry) error {
	if swag.IsZero(m.OpeningWeekendGross) { // not required
		return nil
	}

	if m.OpeningWeekendGross != nil {
		if err := m.OpeningWeekendGross.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("openingWeekendGross")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("openingWeekendGross")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiBoxOffice) validateProductionBudget(formats strfmt.Registry) error {
	if swag.IsZero(m.ProductionBudget) { // not required
		return nil
	}

	if m.ProductionBudget != nil {
		if err := m.ProductionBudget.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("productionBudget")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("productionBudget")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiBoxOffice) validateWorldwideGross(formats strfmt.Registry) error {
	if swag.IsZero(m.WorldwideGross) { // not required
		return nil
	}

	if m.WorldwideGross != nil {
		if err := m.WorldwideGross.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("worldwideGross")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("worldwideGross")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this imdbapi box office based on the context it is used
func (m *ImdbapiBoxOffice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDomesticGross(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOpeningWeekendGross(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProductionBudget(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWorldwideGross(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiBoxOffice) contextValidateDomesticGross(ctx context.Context, formats strfmt.Registry) error {

	if m.DomesticGross != nil {

		if swag.IsZero(m.DomesticGross) { // not required
			return nil
		}

		if err := m.DomesticGross.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("domesticGross")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("domesticGross")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiBoxOffice) contextValidateOpeningWeekendGross(ctx context.Context, formats strfmt.Registry) error {

	if m.OpeningWeekendGross != nil {

		if swag.IsZero(m.OpeningWeekendGross) { // not required
			return nil
		}

		if err := m.OpeningWeekendGross.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("openingWeekendGross")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("openingWeekendGross")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiBoxOffice) contextValidateProductionBudget(ctx context.Context, formats strfmt.Registry) error {

	if m.ProductionBudget != nil {

		if swag.IsZero(m.ProductionBudget) { // not required
			return nil
		}

		if err := m.ProductionBudget.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("productionBudget")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("productionBudget")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiBoxOffice) contextValidateWorldwideGross(ctx context.Context, formats strfmt.Registry) error {

	if m.WorldwideGross != nil {

		if swag.IsZero(m.WorldwideGross) { // not required
			return nil
		}

		if err := m.WorldwideGross.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("worldwideGross")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("worldwideGross")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiBoxOffice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiBoxOffice) UnmarshalBinary(b []byte) error {
	var res ImdbapiBoxOffice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
