// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiMetacritic Metacritic information for a movie or TV show.
//
// swagger:model imdbapiMetacritic
type ImdbapiMetacritic struct {

	// Number of reviews.
	ReviewCount int32 `json:"reviewCount,omitempty"`

	// Metacritic score.
	Score int32 `json:"score,omitempty"`

	// Metacritic URL.
	URL string `json:"url,omitempty"`
}

// Validate validates this imdbapi metacritic
func (m *ImdbapiMetacritic) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi metacritic based on context it is used
func (m *ImdbapiMetacritic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiMetacritic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiMetacritic) UnmarshalBinary(b []byte) error {
	var res ImdbapiMetacritic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
