// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiSeason imdbapi season
//
// swagger:model imdbapiSeason
type ImdbapiSeason struct {

	// episode count
	EpisodeCount int32 `json:"episodeCount,omitempty"`

	// season
	Season string `json:"season,omitempty"`
}

// Validate validates this imdbapi season
func (m *ImdbapiSeason) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi season based on context it is used
func (m *ImdbapiSeason) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiSeason) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiSeason) UnmarshalBinary(b []byte) error {
	var res ImdbapiSeason
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
