// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiMoney imdbapi money
//
// swagger:model imdbapiMoney
type ImdbapiMoney struct {

	// The amount of money in the box office.
	Amount string `json:"amount,omitempty"`

	// The currency of the money.
	Currency string `json:"currency,omitempty"`
}

// Validate validates this imdbapi money
func (m *ImdbapiMoney) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi money based on context it is used
func (m *ImdbapiMoney) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiMoney) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiMoney) UnmarshalBinary(b []byte) error {
	var res ImdbapiMoney
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
