// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiCountry imdbapi country
//
// swagger:model imdbapiCountry
type ImdbapiCountry struct {

	// The ISO 3166-1 alpha-2 country code for the title, (e.g. "US" for the United States, "JP" for Japan)
	Code string `json:"code,omitempty"`

	// The name of the country in English.
	Name string `json:"name,omitempty"`
}

// Validate validates this imdbapi country
func (m *ImdbapiCountry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi country based on context it is used
func (m *ImdbapiCountry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiCountry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiCountry) UnmarshalBinary(b []byte) error {
	var res ImdbapiCountry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
