// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListTitleSeasonsResponse imdbapi list title seasons response
//
// swagger:model imdbapiListTitleSeasonsResponse
type ImdbapiListTitleSeasonsResponse struct {

	// List of seasons associated with the title.
	Seasons []*ImdbapiSeason `json:"seasons"`
}

// Validate validates this imdbapi list title seasons response
func (m *ImdbapiListTitleSeasonsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSeasons(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleSeasonsResponse) validateSeasons(formats strfmt.Registry) error {
	if swag.IsZero(m.Seasons) { // not required
		return nil
	}

	for i := 0; i < len(m.Seasons); i++ {
		if swag.IsZero(m.Seasons[i]) { // not required
			continue
		}

		if m.Seasons[i] != nil {
			if err := m.Seasons[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("seasons" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("seasons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list title seasons response based on the context it is used
func (m *ImdbapiListTitleSeasonsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSeasons(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleSeasonsResponse) contextValidateSeasons(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Seasons); i++ {

		if m.Seasons[i] != nil {

			if swag.IsZero(m.Seasons[i]) { // not required
				return nil
			}

			if err := m.Seasons[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("seasons" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("seasons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListTitleSeasonsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListTitleSeasonsResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListTitleSeasonsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
