// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiInterestCategory InterestCategory represents a category of interests in the IMDB API.
//
// swagger:model imdbapiInterestCategory
type ImdbapiInterestCategory struct {

	// Unique identifier for the interest category.
	Category string `json:"category,omitempty"`

	// A list of interests that belong to this category.
	Interests []*ImdbapiInterest `json:"interests"`
}

// Validate validates this imdbapi interest category
func (m *ImdbapiInterestCategory) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInterests(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiInterestCategory) validateInterests(formats strfmt.Registry) error {
	if swag.IsZero(m.Interests) { // not required
		return nil
	}

	for i := 0; i < len(m.Interests); i++ {
		if swag.IsZero(m.Interests[i]) { // not required
			continue
		}

		if m.Interests[i] != nil {
			if err := m.Interests[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("interests" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("interests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi interest category based on the context it is used
func (m *ImdbapiInterestCategory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInterests(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiInterestCategory) contextValidateInterests(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Interests); i++ {

		if m.Interests[i] != nil {

			if swag.IsZero(m.Interests[i]) { // not required
				return nil
			}

			if err := m.Interests[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("interests" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("interests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiInterestCategory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiInterestCategory) UnmarshalBinary(b []byte) error {
	var res ImdbapiInterestCategory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
