// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiNameTrivia NameTrivia represents a trivia fact about a person (name).
//
// swagger:model imdbapiNameTrivia
type ImdbapiNameTrivia struct {

	// The unique identifier for the trivia.
	ID string `json:"id,omitempty"`

	// The number of users who have expressed interest in this trivia.
	InterestCount int32 `json:"interestCount,omitempty"`

	// The trivia body text.
	Text string `json:"text,omitempty"`

	// The number of votes this trivia has received.
	VoteCount int32 `json:"voteCount,omitempty"`
}

// Validate validates this imdbapi name trivia
func (m *ImdbapiNameTrivia) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi name trivia based on context it is used
func (m *ImdbapiNameTrivia) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiNameTrivia) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiNameTrivia) UnmarshalBinary(b []byte) error {
	var res ImdbapiNameTrivia
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
