// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ImdbapiTitleType TitleType defines the type of title in the IMDb API.
//
//   - MOVIE: Represents a movie title.
//   - TV_SERIES: Represents a TV series title.
//   - TV_MINI_SERIES: Represents a TV mini-series title.
//   - TV_SPECIAL: Represents a TV special title.
//   - TV_MOVIE: Represents a TV movie title.
//   - SHORT: Represents a short title.
//   - VIDEO: Represents a video title.
//   - VIDEO_GAME: Represents a video game title.
//
// swagger:model imdbapiTitleType
type ImdbapiTitleType string

func NewImdbapiTitleType(value ImdbapiTitleType) *ImdbapiTitleType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ImdbapiTitleType.
func (m ImdbapiTitleType) Pointer() *ImdbapiTitleType {
	return &m
}

const (

	// ImdbapiTitleTypeMOVIE captures enum value "MOVIE"
	ImdbapiTitleTypeMOVIE ImdbapiTitleType = "MOVIE"

	// ImdbapiTitleTypeTVSERIES captures enum value "TV_SERIES"
	ImdbapiTitleTypeTVSERIES ImdbapiTitleType = "TV_SERIES"

	// ImdbapiTitleTypeTVMINISERIES captures enum value "TV_MINI_SERIES"
	ImdbapiTitleTypeTVMINISERIES ImdbapiTitleType = "TV_MINI_SERIES"

	// ImdbapiTitleTypeTVSPECIAL captures enum value "TV_SPECIAL"
	ImdbapiTitleTypeTVSPECIAL ImdbapiTitleType = "TV_SPECIAL"

	// ImdbapiTitleTypeTVMOVIE captures enum value "TV_MOVIE"
	ImdbapiTitleTypeTVMOVIE ImdbapiTitleType = "TV_MOVIE"

	// ImdbapiTitleTypeSHORT captures enum value "SHORT"
	ImdbapiTitleTypeSHORT ImdbapiTitleType = "SHORT"

	// ImdbapiTitleTypeVIDEO captures enum value "VIDEO"
	ImdbapiTitleTypeVIDEO ImdbapiTitleType = "VIDEO"

	// ImdbapiTitleTypeVIDEOGAME captures enum value "VIDEO_GAME"
	ImdbapiTitleTypeVIDEOGAME ImdbapiTitleType = "VIDEO_GAME"
)

// for schema
var imdbapiTitleTypeEnum []interface{}

func init() {
	var res []ImdbapiTitleType
	if err := json.Unmarshal([]byte(`["MOVIE","TV_SERIES","TV_MINI_SERIES","TV_SPECIAL","TV_MOVIE","SHORT","VIDEO","VIDEO_GAME"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		imdbapiTitleTypeEnum = append(imdbapiTitleTypeEnum, v)
	}
}

func (m ImdbapiTitleType) validateImdbapiTitleTypeEnum(path, location string, value ImdbapiTitleType) error {
	if err := validate.EnumCase(path, location, value, imdbapiTitleTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this imdbapi title type
func (m ImdbapiTitleType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateImdbapiTitleTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this imdbapi title type based on context it is used
func (m ImdbapiTitleType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
