// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiOpeningWeekendGross imdbapi opening weekend gross
//
// swagger:model imdbapiOpeningWeekendGross
type ImdbapiOpeningWeekendGross struct {

	// The amount of money made in the opening weekend.
	Gross *ImdbapiMoney `json:"gross,omitempty"`

	// The date of the opening weekend.
	WeekendEndDate *ImdbapiPrecisionDate `json:"weekendEndDate,omitempty"`
}

// Validate validates this imdbapi opening weekend gross
func (m *ImdbapiOpeningWeekendGross) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGross(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWeekendEndDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiOpeningWeekendGross) validateGross(formats strfmt.Registry) error {
	if swag.IsZero(m.Gross) { // not required
		return nil
	}

	if m.Gross != nil {
		if err := m.Gross.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gross")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("gross")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiOpeningWeekendGross) validateWeekendEndDate(formats strfmt.Registry) error {
	if swag.IsZero(m.WeekendEndDate) { // not required
		return nil
	}

	if m.WeekendEndDate != nil {
		if err := m.WeekendEndDate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("weekendEndDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("weekendEndDate")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this imdbapi opening weekend gross based on the context it is used
func (m *ImdbapiOpeningWeekendGross) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGross(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWeekendEndDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiOpeningWeekendGross) contextValidateGross(ctx context.Context, formats strfmt.Registry) error {

	if m.Gross != nil {

		if swag.IsZero(m.Gross) { // not required
			return nil
		}

		if err := m.Gross.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gross")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("gross")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiOpeningWeekendGross) contextValidateWeekendEndDate(ctx context.Context, formats strfmt.Registry) error {

	if m.WeekendEndDate != nil {

		if swag.IsZero(m.WeekendEndDate) { // not required
			return nil
		}

		if err := m.WeekendEndDate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("weekendEndDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("weekendEndDate")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiOpeningWeekendGross) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiOpeningWeekendGross) UnmarshalBinary(b []byte) error {
	var res ImdbapiOpeningWeekendGross
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
