// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiInterest Interest represents a specific interest in the IMDB API.
//
// swagger:model imdbapiInterest
type ImdbapiInterest struct {

	// A brief description of the interest, which can include details about the genre or type.
	Description string `json:"description,omitempty"`

	// Unique identifier for the interest.
	ID string `json:"id,omitempty"`

	// Indicates whether the interest is a subgenre of another genre.
	IsSubgenre bool `json:"isSubgenre,omitempty"`

	// The name of the interest, e.g., "Action", "Action Epic", "Adult Animation", etc.
	Name string `json:"name,omitempty"`

	// The primary image of the interest, which can be a poster or cover image.
	PrimaryImage *ImdbapiImage `json:"primaryImage,omitempty"`

	// A list of similar interests that are related to this interest.
	SimilarInterests []*ImdbapiInterest `json:"similarInterests"`
}

// Validate validates this imdbapi interest
func (m *ImdbapiInterest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrimaryImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSimilarInterests(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiInterest) validatePrimaryImage(formats strfmt.Registry) error {
	if swag.IsZero(m.PrimaryImage) { // not required
		return nil
	}

	if m.PrimaryImage != nil {
		if err := m.PrimaryImage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiInterest) validateSimilarInterests(formats strfmt.Registry) error {
	if swag.IsZero(m.SimilarInterests) { // not required
		return nil
	}

	for i := 0; i < len(m.SimilarInterests); i++ {
		if swag.IsZero(m.SimilarInterests[i]) { // not required
			continue
		}

		if m.SimilarInterests[i] != nil {
			if err := m.SimilarInterests[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("similarInterests" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("similarInterests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi interest based on the context it is used
func (m *ImdbapiInterest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePrimaryImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSimilarInterests(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiInterest) contextValidatePrimaryImage(ctx context.Context, formats strfmt.Registry) error {

	if m.PrimaryImage != nil {

		if swag.IsZero(m.PrimaryImage) { // not required
			return nil
		}

		if err := m.PrimaryImage.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiInterest) contextValidateSimilarInterests(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SimilarInterests); i++ {

		if m.SimilarInterests[i] != nil {

			if swag.IsZero(m.SimilarInterests[i]) { // not required
				return nil
			}

			if err := m.SimilarInterests[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("similarInterests" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("similarInterests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiInterest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiInterest) UnmarshalBinary(b []byte) error {
	var res ImdbapiInterest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
