// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiAwardNominationStats imdbapi award nomination stats
//
// swagger:model imdbapiAwardNominationStats
type ImdbapiAwardNominationStats struct {

	// nomination count
	NominationCount int32 `json:"nominationCount,omitempty"`

	// win count
	WinCount int32 `json:"winCount,omitempty"`
}

// Validate validates this imdbapi award nomination stats
func (m *ImdbapiAwardNominationStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi award nomination stats based on context it is used
func (m *ImdbapiAwardNominationStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiAwardNominationStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiAwardNominationStats) UnmarshalBinary(b []byte) error {
	var res ImdbapiAwardNominationStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
