// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListNameFilmographyResponse Response message for listing filmography associated with a name.
//
// swagger:model imdbapiListNameFilmographyResponse
type ImdbapiListNameFilmographyResponse struct {

	// List of filmography credits associated with the name.
	Credits []*ImdbapiCredit `json:"credits"`

	// Token for the next page of results, if applicable.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// Total count of filmography credits associated with the name.
	TotalCount int32 `json:"totalCount,omitempty"`
}

// Validate validates this imdbapi list name filmography response
func (m *ImdbapiListNameFilmographyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCredits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListNameFilmographyResponse) validateCredits(formats strfmt.Registry) error {
	if swag.IsZero(m.Credits) { // not required
		return nil
	}

	for i := 0; i < len(m.Credits); i++ {
		if swag.IsZero(m.Credits[i]) { // not required
			continue
		}

		if m.Credits[i] != nil {
			if err := m.Credits[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("credits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("credits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list name filmography response based on the context it is used
func (m *ImdbapiListNameFilmographyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCredits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListNameFilmographyResponse) contextValidateCredits(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Credits); i++ {

		if m.Credits[i] != nil {

			if swag.IsZero(m.Credits[i]) { // not required
				return nil
			}

			if err := m.Credits[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("credits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("credits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListNameFilmographyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListNameFilmographyResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListNameFilmographyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
