// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiCompanyCredit imdbapi company credit
//
// swagger:model imdbapiCompanyCredit
type ImdbapiCompanyCredit struct {

	// // Additional attributes related to the company credit
	Attributes []string `json:"attributes"`

	// Category of the company credit, such as production, sales, distribution, etc.
	Category string `json:"category,omitempty"`

	// Company associated with the credit.
	Company *ImdbapiCompany `json:"company,omitempty"`

	// Countries where the company is based or operates.
	Countries []*ImdbapiCountry `json:"countries"`

	// YearsInvolved represents the years a company was involved in a project.
	YearsInvolved *ImdbapiYearsInvolved `json:"yearsInvolved,omitempty"`
}

// Validate validates this imdbapi company credit
func (m *ImdbapiCompanyCredit) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompany(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCountries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateYearsInvolved(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiCompanyCredit) validateCompany(formats strfmt.Registry) error {
	if swag.IsZero(m.Company) { // not required
		return nil
	}

	if m.Company != nil {
		if err := m.Company.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("company")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("company")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiCompanyCredit) validateCountries(formats strfmt.Registry) error {
	if swag.IsZero(m.Countries) { // not required
		return nil
	}

	for i := 0; i < len(m.Countries); i++ {
		if swag.IsZero(m.Countries[i]) { // not required
			continue
		}

		if m.Countries[i] != nil {
			if err := m.Countries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("countries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("countries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiCompanyCredit) validateYearsInvolved(formats strfmt.Registry) error {
	if swag.IsZero(m.YearsInvolved) { // not required
		return nil
	}

	if m.YearsInvolved != nil {
		if err := m.YearsInvolved.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("yearsInvolved")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("yearsInvolved")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this imdbapi company credit based on the context it is used
func (m *ImdbapiCompanyCredit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCompany(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCountries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateYearsInvolved(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiCompanyCredit) contextValidateCompany(ctx context.Context, formats strfmt.Registry) error {

	if m.Company != nil {

		if swag.IsZero(m.Company) { // not required
			return nil
		}

		if err := m.Company.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("company")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("company")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiCompanyCredit) contextValidateCountries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Countries); i++ {

		if m.Countries[i] != nil {

			if swag.IsZero(m.Countries[i]) { // not required
				return nil
			}

			if err := m.Countries[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("countries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("countries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiCompanyCredit) contextValidateYearsInvolved(ctx context.Context, formats strfmt.Registry) error {

	if m.YearsInvolved != nil {

		if swag.IsZero(m.YearsInvolved) { // not required
			return nil
		}

		if err := m.YearsInvolved.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("yearsInvolved")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("yearsInvolved")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiCompanyCredit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiCompanyCredit) UnmarshalBinary(b []byte) error {
	var res ImdbapiCompanyCredit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
