// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiEpisode imdbapi episode
//
// swagger:model imdbapiEpisode
type ImdbapiEpisode struct {

	// episode number
	EpisodeNumber int32 `json:"episodeNumber,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// plot
	Plot string `json:"plot,omitempty"`

	// primary image
	PrimaryImage *ImdbapiImage `json:"primaryImage,omitempty"`

	// rating
	Rating *ImdbapiRating `json:"rating,omitempty"`

	// release date
	ReleaseDate *ImdbapiPrecisionDate `json:"releaseDate,omitempty"`

	// runtime seconds
	RuntimeSeconds int32 `json:"runtimeSeconds,omitempty"`

	// season
	Season string `json:"season,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this imdbapi episode
func (m *ImdbapiEpisode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrimaryImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRating(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReleaseDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiEpisode) validatePrimaryImage(formats strfmt.Registry) error {
	if swag.IsZero(m.PrimaryImage) { // not required
		return nil
	}

	if m.PrimaryImage != nil {
		if err := m.PrimaryImage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiEpisode) validateRating(formats strfmt.Registry) error {
	if swag.IsZero(m.Rating) { // not required
		return nil
	}

	if m.Rating != nil {
		if err := m.Rating.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rating")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rating")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiEpisode) validateReleaseDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ReleaseDate) { // not required
		return nil
	}

	if m.ReleaseDate != nil {
		if err := m.ReleaseDate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("releaseDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("releaseDate")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this imdbapi episode based on the context it is used
func (m *ImdbapiEpisode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePrimaryImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRating(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReleaseDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiEpisode) contextValidatePrimaryImage(ctx context.Context, formats strfmt.Registry) error {

	if m.PrimaryImage != nil {

		if swag.IsZero(m.PrimaryImage) { // not required
			return nil
		}

		if err := m.PrimaryImage.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiEpisode) contextValidateRating(ctx context.Context, formats strfmt.Registry) error {

	if m.Rating != nil {

		if swag.IsZero(m.Rating) { // not required
			return nil
		}

		if err := m.Rating.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rating")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rating")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiEpisode) contextValidateReleaseDate(ctx context.Context, formats strfmt.Registry) error {

	if m.ReleaseDate != nil {

		if swag.IsZero(m.ReleaseDate) { // not required
			return nil
		}

		if err := m.ReleaseDate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("releaseDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("releaseDate")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiEpisode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiEpisode) UnmarshalBinary(b []byte) error {
	var res ImdbapiEpisode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
