// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiParentsGuideSeverity imdbapi parents guide severity
//
// swagger:model imdbapiParentsGuideSeverity
type ImdbapiParentsGuideSeverity struct {

	// severity level
	SeverityLevel string `json:"severityLevel,omitempty"`

	// vote count
	VoteCount int32 `json:"voteCount,omitempty"`
}

// Validate validates this imdbapi parents guide severity
func (m *ImdbapiParentsGuideSeverity) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi parents guide severity based on context it is used
func (m *ImdbapiParentsGuideSeverity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiParentsGuideSeverity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiParentsGuideSeverity) UnmarshalBinary(b []byte) error {
	var res ImdbapiParentsGuideSeverity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
