// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ImdbapiParentsGuideCategory ParentsGuideCategory defines the categories for the Parents Guide.
//
//   - SEXUAL_CONTENT: Sex & Nudity
//   - VIOLENCE: Violence & Gore
//   - PROFANITY: Profanity
//   - ALCOHOL_DRUGS: Alcohol, Drugs & Smoking
//   - FRIGHTENING_INTENSE_SCENES: Frightening & Intense Scenes
//
// swagger:model imdbapiParentsGuideCategory
type ImdbapiParentsGuideCategory string

func NewImdbapiParentsGuideCategory(value ImdbapiParentsGuideCategory) *ImdbapiParentsGuideCategory {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ImdbapiParentsGuideCategory.
func (m ImdbapiParentsGuideCategory) Pointer() *ImdbapiParentsGuideCategory {
	return &m
}

const (

	// ImdbapiParentsGuideCategorySEXUALCONTENT captures enum value "SEXUAL_CONTENT"
	ImdbapiParentsGuideCategorySEXUALCONTENT ImdbapiParentsGuideCategory = "SEXUAL_CONTENT"

	// ImdbapiParentsGuideCategoryVIOLENCE captures enum value "VIOLENCE"
	ImdbapiParentsGuideCategoryVIOLENCE ImdbapiParentsGuideCategory = "VIOLENCE"

	// ImdbapiParentsGuideCategoryPROFANITY captures enum value "PROFANITY"
	ImdbapiParentsGuideCategoryPROFANITY ImdbapiParentsGuideCategory = "PROFANITY"

	// ImdbapiParentsGuideCategoryALCOHOLDRUGS captures enum value "ALCOHOL_DRUGS"
	ImdbapiParentsGuideCategoryALCOHOLDRUGS ImdbapiParentsGuideCategory = "ALCOHOL_DRUGS"

	// ImdbapiParentsGuideCategoryFRIGHTENINGINTENSESCENES captures enum value "FRIGHTENING_INTENSE_SCENES"
	ImdbapiParentsGuideCategoryFRIGHTENINGINTENSESCENES ImdbapiParentsGuideCategory = "FRIGHTENING_INTENSE_SCENES"
)

// for schema
var imdbapiParentsGuideCategoryEnum []interface{}

func init() {
	var res []ImdbapiParentsGuideCategory
	if err := json.Unmarshal([]byte(`["SEXUAL_CONTENT","VIOLENCE","PROFANITY","ALCOHOL_DRUGS","FRIGHTENING_INTENSE_SCENES"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		imdbapiParentsGuideCategoryEnum = append(imdbapiParentsGuideCategoryEnum, v)
	}
}

func (m ImdbapiParentsGuideCategory) validateImdbapiParentsGuideCategoryEnum(path, location string, value ImdbapiParentsGuideCategory) error {
	if err := validate.EnumCase(path, location, value, imdbapiParentsGuideCategoryEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this imdbapi parents guide category
func (m ImdbapiParentsGuideCategory) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateImdbapiParentsGuideCategoryEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this imdbapi parents guide category based on context it is used
func (m ImdbapiParentsGuideCategory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
