// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiParentsGuide imdbapi parents guide
//
// swagger:model imdbapiParentsGuide
type ImdbapiParentsGuide struct {

	// category
	Category ImdbapiParentsGuideCategory `json:"category,omitempty"`

	// reviews
	Reviews []*ImdbapiParentsGuideReview `json:"reviews"`

	// severity breakdowns
	SeverityBreakdowns []*ImdbapiParentsGuideSeverity `json:"severityBreakdowns"`
}

// Validate validates this imdbapi parents guide
func (m *ImdbapiParentsGuide) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCategory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReviews(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeverityBreakdowns(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiParentsGuide) validateCategory(formats strfmt.Registry) error {
	if swag.IsZero(m.Category) { // not required
		return nil
	}

	if err := m.Category.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("category")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("category")
		}
		return err
	}

	return nil
}

func (m *ImdbapiParentsGuide) validateReviews(formats strfmt.Registry) error {
	if swag.IsZero(m.Reviews) { // not required
		return nil
	}

	for i := 0; i < len(m.Reviews); i++ {
		if swag.IsZero(m.Reviews[i]) { // not required
			continue
		}

		if m.Reviews[i] != nil {
			if err := m.Reviews[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("reviews" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("reviews" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiParentsGuide) validateSeverityBreakdowns(formats strfmt.Registry) error {
	if swag.IsZero(m.SeverityBreakdowns) { // not required
		return nil
	}

	for i := 0; i < len(m.SeverityBreakdowns); i++ {
		if swag.IsZero(m.SeverityBreakdowns[i]) { // not required
			continue
		}

		if m.SeverityBreakdowns[i] != nil {
			if err := m.SeverityBreakdowns[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("severityBreakdowns" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("severityBreakdowns" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi parents guide based on the context it is used
func (m *ImdbapiParentsGuide) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCategory(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReviews(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSeverityBreakdowns(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiParentsGuide) contextValidateCategory(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Category) { // not required
		return nil
	}

	if err := m.Category.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("category")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("category")
		}
		return err
	}

	return nil
}

func (m *ImdbapiParentsGuide) contextValidateReviews(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Reviews); i++ {

		if m.Reviews[i] != nil {

			if swag.IsZero(m.Reviews[i]) { // not required
				return nil
			}

			if err := m.Reviews[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("reviews" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("reviews" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiParentsGuide) contextValidateSeverityBreakdowns(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SeverityBreakdowns); i++ {

		if m.SeverityBreakdowns[i] != nil {

			if swag.IsZero(m.SeverityBreakdowns[i]) { // not required
				return nil
			}

			if err := m.SeverityBreakdowns[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("severityBreakdowns" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("severityBreakdowns" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiParentsGuide) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiParentsGuide) UnmarshalBinary(b []byte) error {
	var res ImdbapiParentsGuide
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
