// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListTitleVideosResponse imdbapi list title videos response
//
// swagger:model imdbapiListTitleVideosResponse
type ImdbapiListTitleVideosResponse struct {

	// Token for the next page of results, if applicable.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// Total count of videos associated with the title.
	TotalCount int32 `json:"totalCount,omitempty"`

	// List of videos associated with the title.
	Videos []*ImdbapiVideo `json:"videos"`
}

// Validate validates this imdbapi list title videos response
func (m *ImdbapiListTitleVideosResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVideos(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleVideosResponse) validateVideos(formats strfmt.Registry) error {
	if swag.IsZero(m.Videos) { // not required
		return nil
	}

	for i := 0; i < len(m.Videos); i++ {
		if swag.IsZero(m.Videos[i]) { // not required
			continue
		}

		if m.Videos[i] != nil {
			if err := m.Videos[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("videos" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("videos" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list title videos response based on the context it is used
func (m *ImdbapiListTitleVideosResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateVideos(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleVideosResponse) contextValidateVideos(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Videos); i++ {

		if m.Videos[i] != nil {

			if swag.IsZero(m.Videos[i]) { // not required
				return nil
			}

			if err := m.Videos[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("videos" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("videos" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListTitleVideosResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListTitleVideosResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListTitleVideosResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
