// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListTitleAKAsResponse Response message for listing AKAs (Also Known As) associated with a title.
//
// swagger:model imdbapiListTitleAKAsResponse
type ImdbapiListTitleAKAsResponse struct {

	// List of AKAs associated with the title.
	Akas []*ImdbapiAKA `json:"akas"`
}

// Validate validates this imdbapi list title a k as response
func (m *ImdbapiListTitleAKAsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAkas(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleAKAsResponse) validateAkas(formats strfmt.Registry) error {
	if swag.IsZero(m.Akas) { // not required
		return nil
	}

	for i := 0; i < len(m.Akas); i++ {
		if swag.IsZero(m.Akas[i]) { // not required
			continue
		}

		if m.Akas[i] != nil {
			if err := m.Akas[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("akas" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("akas" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list title a k as response based on the context it is used
func (m *ImdbapiListTitleAKAsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAkas(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleAKAsResponse) contextValidateAkas(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Akas); i++ {

		if m.Akas[i] != nil {

			if swag.IsZero(m.Akas[i]) { // not required
				return nil
			}

			if err := m.Akas[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("akas" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("akas" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListTitleAKAsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListTitleAKAsResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListTitleAKAsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
