// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListTitlesResponse Response message for listing titles.
//
// swagger:model imdbapiListTitlesResponse
type ImdbapiListTitlesResponse struct {

	// Token for the next page of results, if applicable.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// List of titles matching the request criteria.
	Titles []*ImdbapiTitle `json:"titles"`

	// Total number of titles matching the request criteria.
	TotalCount int32 `json:"totalCount,omitempty"`
}

// Validate validates this imdbapi list titles response
func (m *ImdbapiListTitlesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTitles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitlesResponse) validateTitles(formats strfmt.Registry) error {
	if swag.IsZero(m.Titles) { // not required
		return nil
	}

	for i := 0; i < len(m.Titles); i++ {
		if swag.IsZero(m.Titles[i]) { // not required
			continue
		}

		if m.Titles[i] != nil {
			if err := m.Titles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("titles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("titles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list titles response based on the context it is used
func (m *ImdbapiListTitlesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTitles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitlesResponse) contextValidateTitles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Titles); i++ {

		if m.Titles[i] != nil {

			if swag.IsZero(m.Titles[i]) { // not required
				return nil
			}

			if err := m.Titles[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("titles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("titles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListTitlesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListTitlesResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListTitlesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
