// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiEvent imdbapi event
//
// swagger:model imdbapiEvent
type ImdbapiEvent struct {

	// The unique identifier for the event.
	ID string `json:"id,omitempty"`

	// The name of the event.
	Name string `json:"name,omitempty"`
}

// Validate validates this imdbapi event
func (m *ImdbapiEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi event based on context it is used
func (m *ImdbapiEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiEvent) UnmarshalBinary(b []byte) error {
	var res ImdbapiEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
