// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListNameTriviaResponse Response message for listing trivia associated with a name.
//
// swagger:model imdbapiListNameTriviaResponse
type ImdbapiListNameTriviaResponse struct {

	// Token for the next page of results, if applicable.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// Total count of trivia entries associated with the name.
	TotalCount int32 `json:"totalCount,omitempty"`

	// List of trivia entries associated with the name.
	TriviaEntries []*ImdbapiNameTrivia `json:"triviaEntries"`
}

// Validate validates this imdbapi list name trivia response
func (m *ImdbapiListNameTriviaResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTriviaEntries(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListNameTriviaResponse) validateTriviaEntries(formats strfmt.Registry) error {
	if swag.IsZero(m.TriviaEntries) { // not required
		return nil
	}

	for i := 0; i < len(m.TriviaEntries); i++ {
		if swag.IsZero(m.TriviaEntries[i]) { // not required
			continue
		}

		if m.TriviaEntries[i] != nil {
			if err := m.TriviaEntries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("triviaEntries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("triviaEntries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list name trivia response based on the context it is used
func (m *ImdbapiListNameTriviaResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTriviaEntries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListNameTriviaResponse) contextValidateTriviaEntries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TriviaEntries); i++ {

		if m.TriviaEntries[i] != nil {

			if swag.IsZero(m.TriviaEntries[i]) { // not required
				return nil
			}

			if err := m.TriviaEntries[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("triviaEntries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("triviaEntries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListNameTriviaResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListNameTriviaResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListNameTriviaResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
