// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiReleaseDate The ReleaseDate message represents the release date of a title in a specific country.
//
// swagger:model imdbapiReleaseDate
type ImdbapiReleaseDate struct {

	// The attributes field contains additional attributes related to the release date.
	//
	// These attributes can include information such as
	// the format of the release (e.g., "Theatrical", "DVD", "Blu-ray").
	Attributes []string `json:"attributes"`

	// The country where the title was released,
	Country *ImdbapiCountry `json:"country,omitempty"`

	// The date when the title was released in the specified country.
	ReleaseDate *ImdbapiPrecisionDate `json:"releaseDate,omitempty"`
}

// Validate validates this imdbapi release date
func (m *ImdbapiReleaseDate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCountry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReleaseDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiReleaseDate) validateCountry(formats strfmt.Registry) error {
	if swag.IsZero(m.Country) { // not required
		return nil
	}

	if m.Country != nil {
		if err := m.Country.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("country")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("country")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiReleaseDate) validateReleaseDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ReleaseDate) { // not required
		return nil
	}

	if m.ReleaseDate != nil {
		if err := m.ReleaseDate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("releaseDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("releaseDate")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this imdbapi release date based on the context it is used
func (m *ImdbapiReleaseDate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCountry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReleaseDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiReleaseDate) contextValidateCountry(ctx context.Context, formats strfmt.Registry) error {

	if m.Country != nil {

		if swag.IsZero(m.Country) { // not required
			return nil
		}

		if err := m.Country.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("country")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("country")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiReleaseDate) contextValidateReleaseDate(ctx context.Context, formats strfmt.Registry) error {

	if m.ReleaseDate != nil {

		if swag.IsZero(m.ReleaseDate) { // not required
			return nil
		}

		if err := m.ReleaseDate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("releaseDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("releaseDate")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiReleaseDate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiReleaseDate) UnmarshalBinary(b []byte) error {
	var res ImdbapiReleaseDate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
