// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiParentsGuideReview imdbapi parents guide review
//
// swagger:model imdbapiParentsGuideReview
type ImdbapiParentsGuideReview struct {

	// is spoiler
	IsSpoiler bool `json:"isSpoiler,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this imdbapi parents guide review
func (m *ImdbapiParentsGuideReview) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi parents guide review based on context it is used
func (m *ImdbapiParentsGuideReview) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiParentsGuideReview) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiParentsGuideReview) UnmarshalBinary(b []byte) error {
	var res ImdbapiParentsGuideReview
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
