// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiLanguage The AKA (Also Known As) message represents alternative titles
// for a movie or TV show in different languages and countries.
//
// swagger:model imdbapiLanguage
type ImdbapiLanguage struct {

	// The ISO 639-3 language code for the title, (e.g. "eng" for English, "jpn" for Japanese)
	Code string `json:"code,omitempty"`

	// The name of the language in English.
	Name string `json:"name,omitempty"`
}

// Validate validates this imdbapi language
func (m *ImdbapiLanguage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi language based on context it is used
func (m *ImdbapiLanguage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiLanguage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiLanguage) UnmarshalBinary(b []byte) error {
	var res ImdbapiLanguage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
