// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListTitleParentsGuideResponse Response message for listing parents guide associated with a title.
//
// swagger:model imdbapiListTitleParentsGuideResponse
type ImdbapiListTitleParentsGuideResponse struct {

	// List of parents guide entries associated with the title.
	ParentsGuide []*ImdbapiParentsGuide `json:"parentsGuide"`
}

// Validate validates this imdbapi list title parents guide response
func (m *ImdbapiListTitleParentsGuideResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParentsGuide(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleParentsGuideResponse) validateParentsGuide(formats strfmt.Registry) error {
	if swag.IsZero(m.ParentsGuide) { // not required
		return nil
	}

	for i := 0; i < len(m.ParentsGuide); i++ {
		if swag.IsZero(m.ParentsGuide[i]) { // not required
			continue
		}

		if m.ParentsGuide[i] != nil {
			if err := m.ParentsGuide[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("parentsGuide" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("parentsGuide" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list title parents guide response based on the context it is used
func (m *ImdbapiListTitleParentsGuideResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParentsGuide(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleParentsGuideResponse) contextValidateParentsGuide(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ParentsGuide); i++ {

		if m.ParentsGuide[i] != nil {

			if swag.IsZero(m.ParentsGuide[i]) { // not required
				return nil
			}

			if err := m.ParentsGuide[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("parentsGuide" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("parentsGuide" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListTitleParentsGuideResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListTitleParentsGuideResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListTitleParentsGuideResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
