// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListTitleEpisodesResponse imdbapi list title episodes response
//
// swagger:model imdbapiListTitleEpisodesResponse
type ImdbapiListTitleEpisodesResponse struct {

	// List of episodes associated with the title.
	Episodes []*ImdbapiEpisode `json:"episodes"`

	// Token for the next page of results, if applicable.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// The total number of episodes that have aired for this title.
	TotalCount int32 `json:"totalCount,omitempty"`
}

// Validate validates this imdbapi list title episodes response
func (m *ImdbapiListTitleEpisodesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEpisodes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleEpisodesResponse) validateEpisodes(formats strfmt.Registry) error {
	if swag.IsZero(m.Episodes) { // not required
		return nil
	}

	for i := 0; i < len(m.Episodes); i++ {
		if swag.IsZero(m.Episodes[i]) { // not required
			continue
		}

		if m.Episodes[i] != nil {
			if err := m.Episodes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("episodes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("episodes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list title episodes response based on the context it is used
func (m *ImdbapiListTitleEpisodesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEpisodes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleEpisodesResponse) contextValidateEpisodes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Episodes); i++ {

		if m.Episodes[i] != nil {

			if swag.IsZero(m.Episodes[i]) { // not required
				return nil
			}

			if err := m.Episodes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("episodes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("episodes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListTitleEpisodesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListTitleEpisodesResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListTitleEpisodesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
