// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ImdbapiTitleSortBy  - SORT_BY_POPULARITY: Sort by popularity.
// This is used to rank titles based on their popularity, which can be influenced by various factors
// such as viewership, ratings, and cultural impact.
//   - SORT_BY_RELEASE_DATE: Sort by release date.
//
// This is used to rank titles based on their release dates, with newer titles typically appearing
// before older ones.
//   - SORT_BY_USER_RATING: Sort by user rating.
//
// This is used to rank titles based on the average user rating, which reflects the overall audience reception.
//   - SORT_BY_USER_RATING_COUNT: Sort by user rating count.
//
// This is used to rank titles based on the number of user ratings they have received,
// which can indicate the level of engagement or popularity among viewers.
//   - SORT_BY_YEAR: Sort by year.
//
// This is used to rank titles based on their release year, with newer titles typically appearing before older ones.
//
// swagger:model imdbapiTitleSortBy
type ImdbapiTitleSortBy string

func NewImdbapiTitleSortBy(value ImdbapiTitleSortBy) *ImdbapiTitleSortBy {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ImdbapiTitleSortBy.
func (m ImdbapiTitleSortBy) Pointer() *ImdbapiTitleSortBy {
	return &m
}

const (

	// ImdbapiTitleSortBySORTBYPOPULARITY captures enum value "SORT_BY_POPULARITY"
	ImdbapiTitleSortBySORTBYPOPULARITY ImdbapiTitleSortBy = "SORT_BY_POPULARITY"

	// ImdbapiTitleSortBySORTBYRELEASEDATE captures enum value "SORT_BY_RELEASE_DATE"
	ImdbapiTitleSortBySORTBYRELEASEDATE ImdbapiTitleSortBy = "SORT_BY_RELEASE_DATE"

	// ImdbapiTitleSortBySORTBYUSERRATING captures enum value "SORT_BY_USER_RATING"
	ImdbapiTitleSortBySORTBYUSERRATING ImdbapiTitleSortBy = "SORT_BY_USER_RATING"

	// ImdbapiTitleSortBySORTBYUSERRATINGCOUNT captures enum value "SORT_BY_USER_RATING_COUNT"
	ImdbapiTitleSortBySORTBYUSERRATINGCOUNT ImdbapiTitleSortBy = "SORT_BY_USER_RATING_COUNT"

	// ImdbapiTitleSortBySORTBYYEAR captures enum value "SORT_BY_YEAR"
	ImdbapiTitleSortBySORTBYYEAR ImdbapiTitleSortBy = "SORT_BY_YEAR"
)

// for schema
var imdbapiTitleSortByEnum []interface{}

func init() {
	var res []ImdbapiTitleSortBy
	if err := json.Unmarshal([]byte(`["SORT_BY_POPULARITY","SORT_BY_RELEASE_DATE","SORT_BY_USER_RATING","SORT_BY_USER_RATING_COUNT","SORT_BY_YEAR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		imdbapiTitleSortByEnum = append(imdbapiTitleSortByEnum, v)
	}
}

func (m ImdbapiTitleSortBy) validateImdbapiTitleSortByEnum(path, location string, value ImdbapiTitleSortBy) error {
	if err := validate.EnumCase(path, location, value, imdbapiTitleSortByEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this imdbapi title sort by
func (m ImdbapiTitleSortBy) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateImdbapiTitleSortByEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this imdbapi title sort by based on context it is used
func (m ImdbapiTitleSortBy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
