// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiAKA The AKA (Also Known As) message represents alternative titles
// for a movie or TV show in different languages and countries.
//
// swagger:model imdbapiAKA
type ImdbapiAKA struct {

	// Additional attributes related to the title,
	// such as "original title", "working title", or "alternative title".
	Attributes []string `json:"attributes"`

	// The country where this title is used, represented by its ISO 3166-1 alpha-2 code.
	Country *ImdbapiCountry `json:"country,omitempty"`

	// The language of the title, represented by its ISO 639-3 code.
	Language *ImdbapiLanguage `json:"language,omitempty"`

	// The display text of the title in the specified language and country.
	Text string `json:"text,omitempty"`
}

// Validate validates this imdbapi a k a
func (m *ImdbapiAKA) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCountry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLanguage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiAKA) validateCountry(formats strfmt.Registry) error {
	if swag.IsZero(m.Country) { // not required
		return nil
	}

	if m.Country != nil {
		if err := m.Country.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("country")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("country")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiAKA) validateLanguage(formats strfmt.Registry) error {
	if swag.IsZero(m.Language) { // not required
		return nil
	}

	if m.Language != nil {
		if err := m.Language.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("language")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("language")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this imdbapi a k a based on the context it is used
func (m *ImdbapiAKA) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCountry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLanguage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiAKA) contextValidateCountry(ctx context.Context, formats strfmt.Registry) error {

	if m.Country != nil {

		if swag.IsZero(m.Country) { // not required
			return nil
		}

		if err := m.Country.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("country")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("country")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiAKA) contextValidateLanguage(ctx context.Context, formats strfmt.Registry) error {

	if m.Language != nil {

		if swag.IsZero(m.Language) { // not required
			return nil
		}

		if err := m.Language.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("language")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("language")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiAKA) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiAKA) UnmarshalBinary(b []byte) error {
	var res ImdbapiAKA
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
