// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiVideo Video is a message that represents a video associated with a title.
//
// swagger:model imdbapiVideo
type ImdbapiVideo struct {

	// A description of the video.
	Description string `json:"description,omitempty"`

	// The height of the video in pixels.
	Height int32 `json:"height,omitempty"`

	// The unique identifier for the video.
	ID string `json:"id,omitempty"`

	// The name of the video.
	Name string `json:"name,omitempty"`

	// The primary image of the video.
	PrimaryImage *ImdbapiImage `json:"primaryImage,omitempty"`

	// The runtime of the video in seconds.
	RuntimeSeconds int32 `json:"runtimeSeconds,omitempty"`

	// The type of the video.
	Type string `json:"type,omitempty"`

	// The width of the video in pixels.
	Width int32 `json:"width,omitempty"`
}

// Validate validates this imdbapi video
func (m *ImdbapiVideo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrimaryImage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiVideo) validatePrimaryImage(formats strfmt.Registry) error {
	if swag.IsZero(m.PrimaryImage) { // not required
		return nil
	}

	if m.PrimaryImage != nil {
		if err := m.PrimaryImage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this imdbapi video based on the context it is used
func (m *ImdbapiVideo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePrimaryImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiVideo) contextValidatePrimaryImage(ctx context.Context, formats strfmt.Registry) error {

	if m.PrimaryImage != nil {

		if swag.IsZero(m.PrimaryImage) { // not required
			return nil
		}

		if err := m.PrimaryImage.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiVideo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiVideo) UnmarshalBinary(b []byte) error {
	var res ImdbapiVideo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
