// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiTitle imdbapi title
//
// swagger:model imdbapiTitle
type ImdbapiTitle struct {

	// The list of directors associated with the title, which can include multiple directors.
	Directors []*ImdbapiName `json:"directors"`

	// The end_year field is used for titles that have a defined end, such as TV series.
	EndYear int32 `json:"endYear,omitempty"`

	// The genres field contains a list of genres associated with the title.
	Genres []string `json:"genres"`

	// The unique identifier for the title.
	ID string `json:"id,omitempty"`

	// The list of interests associated with the title.
	Interests []*ImdbapiInterest `json:"interests"`

	// The is_adult field indicates whether the title is intended for adult audiences.
	IsAdult bool `json:"isAdult,omitempty"`

	// The metacritic information for the title, such as score and reviews.
	Metacritic *ImdbapiMetacritic `json:"metacritic,omitempty"`

	// The list of countries where the title was produced or is associated with.
	OriginCountries []*ImdbapiCountry `json:"originCountries"`

	// The original title of the title, normally which is the title as it was originally released.
	OriginalTitle string `json:"originalTitle,omitempty"`

	// The plot field contains a brief summary or description of the title's storyline.
	Plot string `json:"plot,omitempty"`

	// The primary image associated with the title, such as a poster.
	PrimaryImage *ImdbapiImage `json:"primaryImage,omitempty"`

	// The primary title of the title, which is typically the most recognized name.
	PrimaryTitle string `json:"primaryTitle,omitempty"`

	// The rating field contains the aggregate rating and the number of votes for the title.
	Rating *ImdbapiRating `json:"rating,omitempty"`

	// The runtime_seconds field contains the total runtime of the title in minutes.
	RuntimeSeconds int32 `json:"runtimeSeconds,omitempty"`

	// The list of languages spoken in the title, which can include multiple languages.
	SpokenLanguages []*ImdbapiLanguage `json:"spokenLanguages"`

	// The list of stars associated with the title, which can include multiple actors or actresses.
	Stars []*ImdbapiName `json:"stars"`

	// The start_year field is used for titles that have a defined start, such as movies or TV series.
	StartYear int32 `json:"startYear,omitempty"`

	// The type of the title, such as "movie", "tvSeries", "tvEpisode", etc.
	Type string `json:"type,omitempty"`

	// The list of writers associated with the title, which can include multiple writers.
	Writers []*ImdbapiName `json:"writers"`
}

// Validate validates this imdbapi title
func (m *ImdbapiTitle) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirectors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInterests(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetacritic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOriginCountries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrimaryImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRating(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSpokenLanguages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStars(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWriters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiTitle) validateDirectors(formats strfmt.Registry) error {
	if swag.IsZero(m.Directors) { // not required
		return nil
	}

	for i := 0; i < len(m.Directors); i++ {
		if swag.IsZero(m.Directors[i]) { // not required
			continue
		}

		if m.Directors[i] != nil {
			if err := m.Directors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("directors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("directors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) validateInterests(formats strfmt.Registry) error {
	if swag.IsZero(m.Interests) { // not required
		return nil
	}

	for i := 0; i < len(m.Interests); i++ {
		if swag.IsZero(m.Interests[i]) { // not required
			continue
		}

		if m.Interests[i] != nil {
			if err := m.Interests[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("interests" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("interests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) validateMetacritic(formats strfmt.Registry) error {
	if swag.IsZero(m.Metacritic) { // not required
		return nil
	}

	if m.Metacritic != nil {
		if err := m.Metacritic.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metacritic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metacritic")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiTitle) validateOriginCountries(formats strfmt.Registry) error {
	if swag.IsZero(m.OriginCountries) { // not required
		return nil
	}

	for i := 0; i < len(m.OriginCountries); i++ {
		if swag.IsZero(m.OriginCountries[i]) { // not required
			continue
		}

		if m.OriginCountries[i] != nil {
			if err := m.OriginCountries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("originCountries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("originCountries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) validatePrimaryImage(formats strfmt.Registry) error {
	if swag.IsZero(m.PrimaryImage) { // not required
		return nil
	}

	if m.PrimaryImage != nil {
		if err := m.PrimaryImage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiTitle) validateRating(formats strfmt.Registry) error {
	if swag.IsZero(m.Rating) { // not required
		return nil
	}

	if m.Rating != nil {
		if err := m.Rating.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rating")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rating")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiTitle) validateSpokenLanguages(formats strfmt.Registry) error {
	if swag.IsZero(m.SpokenLanguages) { // not required
		return nil
	}

	for i := 0; i < len(m.SpokenLanguages); i++ {
		if swag.IsZero(m.SpokenLanguages[i]) { // not required
			continue
		}

		if m.SpokenLanguages[i] != nil {
			if err := m.SpokenLanguages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spokenLanguages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spokenLanguages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) validateStars(formats strfmt.Registry) error {
	if swag.IsZero(m.Stars) { // not required
		return nil
	}

	for i := 0; i < len(m.Stars); i++ {
		if swag.IsZero(m.Stars[i]) { // not required
			continue
		}

		if m.Stars[i] != nil {
			if err := m.Stars[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stars" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stars" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) validateWriters(formats strfmt.Registry) error {
	if swag.IsZero(m.Writers) { // not required
		return nil
	}

	for i := 0; i < len(m.Writers); i++ {
		if swag.IsZero(m.Writers[i]) { // not required
			continue
		}

		if m.Writers[i] != nil {
			if err := m.Writers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("writers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("writers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi title based on the context it is used
func (m *ImdbapiTitle) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDirectors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInterests(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMetacritic(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOriginCountries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePrimaryImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRating(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSpokenLanguages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStars(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWriters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiTitle) contextValidateDirectors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Directors); i++ {

		if m.Directors[i] != nil {

			if swag.IsZero(m.Directors[i]) { // not required
				return nil
			}

			if err := m.Directors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("directors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("directors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) contextValidateInterests(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Interests); i++ {

		if m.Interests[i] != nil {

			if swag.IsZero(m.Interests[i]) { // not required
				return nil
			}

			if err := m.Interests[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("interests" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("interests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) contextValidateMetacritic(ctx context.Context, formats strfmt.Registry) error {

	if m.Metacritic != nil {

		if swag.IsZero(m.Metacritic) { // not required
			return nil
		}

		if err := m.Metacritic.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metacritic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metacritic")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiTitle) contextValidateOriginCountries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.OriginCountries); i++ {

		if m.OriginCountries[i] != nil {

			if swag.IsZero(m.OriginCountries[i]) { // not required
				return nil
			}

			if err := m.OriginCountries[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("originCountries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("originCountries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) contextValidatePrimaryImage(ctx context.Context, formats strfmt.Registry) error {

	if m.PrimaryImage != nil {

		if swag.IsZero(m.PrimaryImage) { // not required
			return nil
		}

		if err := m.PrimaryImage.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiTitle) contextValidateRating(ctx context.Context, formats strfmt.Registry) error {

	if m.Rating != nil {

		if swag.IsZero(m.Rating) { // not required
			return nil
		}

		if err := m.Rating.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rating")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rating")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiTitle) contextValidateSpokenLanguages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SpokenLanguages); i++ {

		if m.SpokenLanguages[i] != nil {

			if swag.IsZero(m.SpokenLanguages[i]) { // not required
				return nil
			}

			if err := m.SpokenLanguages[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spokenLanguages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spokenLanguages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) contextValidateStars(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Stars); i++ {

		if m.Stars[i] != nil {

			if swag.IsZero(m.Stars[i]) { // not required
				return nil
			}

			if err := m.Stars[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stars" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stars" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiTitle) contextValidateWriters(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Writers); i++ {

		if m.Writers[i] != nil {

			if swag.IsZero(m.Writers[i]) { // not required
				return nil
			}

			if err := m.Writers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("writers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("writers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiTitle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiTitle) UnmarshalBinary(b []byte) error {
	var res ImdbapiTitle
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
