// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListTitleCompanyCreditsResponse Response message for listing company credits associated with a title.
//
// swagger:model imdbapiListTitleCompanyCreditsResponse
type ImdbapiListTitleCompanyCreditsResponse struct {

	// List of company credits associated with the title.
	CompanyCredits []*ImdbapiCompanyCredit `json:"companyCredits"`

	// Token for the next page of results, if applicable.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// Total count of company credits matched for listing.
	TotalCount int32 `json:"totalCount,omitempty"`
}

// Validate validates this imdbapi list title company credits response
func (m *ImdbapiListTitleCompanyCreditsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompanyCredits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleCompanyCreditsResponse) validateCompanyCredits(formats strfmt.Registry) error {
	if swag.IsZero(m.CompanyCredits) { // not required
		return nil
	}

	for i := 0; i < len(m.CompanyCredits); i++ {
		if swag.IsZero(m.CompanyCredits[i]) { // not required
			continue
		}

		if m.CompanyCredits[i] != nil {
			if err := m.CompanyCredits[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("companyCredits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("companyCredits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list title company credits response based on the context it is used
func (m *ImdbapiListTitleCompanyCreditsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCompanyCredits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleCompanyCreditsResponse) contextValidateCompanyCredits(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CompanyCredits); i++ {

		if m.CompanyCredits[i] != nil {

			if swag.IsZero(m.CompanyCredits[i]) { // not required
				return nil
			}

			if err := m.CompanyCredits[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("companyCredits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("companyCredits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListTitleCompanyCreditsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListTitleCompanyCreditsResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListTitleCompanyCreditsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
