// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiCompany imdbapi company
//
// swagger:model imdbapiCompany
type ImdbapiCompany struct {

	// Unique identifier for the company.
	ID string `json:"id,omitempty"`

	// Name of the company.
	Name string `json:"name,omitempty"`
}

// Validate validates this imdbapi company
func (m *ImdbapiCompany) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi company based on context it is used
func (m *ImdbapiCompany) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiCompany) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiCompany) UnmarshalBinary(b []byte) error {
	var res ImdbapiCompany
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
