// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiPrecisionDate The PrecisionDate message represents a specific date,
// typically used for birth dates, death dates, or release dates.
//
// swagger:model imdbapiPrecisionDate
type ImdbapiPrecisionDate struct {

	// The day of the date, represented as an integer.
	Day int32 `json:"day,omitempty"`

	// The month of the date, represented as an integer.
	Month int32 `json:"month,omitempty"`

	// The year of the date, represented as an integer.
	Year int32 `json:"year,omitempty"`
}

// Validate validates this imdbapi precision date
func (m *ImdbapiPrecisionDate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi precision date based on context it is used
func (m *ImdbapiPrecisionDate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiPrecisionDate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiPrecisionDate) UnmarshalBinary(b []byte) error {
	var res ImdbapiPrecisionDate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
