// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListTitleReleaseDatesResponse Response message for listing release dates associated with a title.
//
// swagger:model imdbapiListTitleReleaseDatesResponse
type ImdbapiListTitleReleaseDatesResponse struct {

	// Token for the next page of results, if applicable.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// List of release dates associated with the title.
	ReleaseDates []*ImdbapiReleaseDate `json:"releaseDates"`
}

// Validate validates this imdbapi list title release dates response
func (m *ImdbapiListTitleReleaseDatesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReleaseDates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleReleaseDatesResponse) validateReleaseDates(formats strfmt.Registry) error {
	if swag.IsZero(m.ReleaseDates) { // not required
		return nil
	}

	for i := 0; i < len(m.ReleaseDates); i++ {
		if swag.IsZero(m.ReleaseDates[i]) { // not required
			continue
		}

		if m.ReleaseDates[i] != nil {
			if err := m.ReleaseDates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("releaseDates" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("releaseDates" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi list title release dates response based on the context it is used
func (m *ImdbapiListTitleReleaseDatesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReleaseDates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleReleaseDatesResponse) contextValidateReleaseDates(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ReleaseDates); i++ {

		if m.ReleaseDates[i] != nil {

			if swag.IsZero(m.ReleaseDates[i]) { // not required
				return nil
			}

			if err := m.ReleaseDates[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("releaseDates" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("releaseDates" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListTitleReleaseDatesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListTitleReleaseDatesResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListTitleReleaseDatesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
