// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiListTitleAwardNominationsResponse Response message for listing award nominations associated with a title.
//
// swagger:model imdbapiListTitleAwardNominationsResponse
type ImdbapiListTitleAwardNominationsResponse struct {

	// List of award nominations associated with the title.
	AwardNominations []*ImdbapiAwardNomination `json:"awardNominations"`

	// Token for the next page of results, if applicable.
	NextPageToken string `json:"nextPageToken,omitempty"`

	// Statistics about award nominations for the title.
	Stats *ImdbapiAwardNominationStats `json:"stats,omitempty"`
}

// Validate validates this imdbapi list title award nominations response
func (m *ImdbapiListTitleAwardNominationsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAwardNominations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStats(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleAwardNominationsResponse) validateAwardNominations(formats strfmt.Registry) error {
	if swag.IsZero(m.AwardNominations) { // not required
		return nil
	}

	for i := 0; i < len(m.AwardNominations); i++ {
		if swag.IsZero(m.AwardNominations[i]) { // not required
			continue
		}

		if m.AwardNominations[i] != nil {
			if err := m.AwardNominations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("awardNominations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("awardNominations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiListTitleAwardNominationsResponse) validateStats(formats strfmt.Registry) error {
	if swag.IsZero(m.Stats) { // not required
		return nil
	}

	if m.Stats != nil {
		if err := m.Stats.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stats")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stats")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this imdbapi list title award nominations response based on the context it is used
func (m *ImdbapiListTitleAwardNominationsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAwardNominations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStats(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiListTitleAwardNominationsResponse) contextValidateAwardNominations(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AwardNominations); i++ {

		if m.AwardNominations[i] != nil {

			if swag.IsZero(m.AwardNominations[i]) { // not required
				return nil
			}

			if err := m.AwardNominations[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("awardNominations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("awardNominations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiListTitleAwardNominationsResponse) contextValidateStats(ctx context.Context, formats strfmt.Registry) error {

	if m.Stats != nil {

		if swag.IsZero(m.Stats) { // not required
			return nil
		}

		if err := m.Stats.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stats")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stats")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiListTitleAwardNominationsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiListTitleAwardNominationsResponse) UnmarshalBinary(b []byte) error {
	var res ImdbapiListTitleAwardNominationsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
