// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiName The Name message represents a person in the IMDb database,
// such as an actor, director, or producer.
//
// swagger:model imdbapiName
type ImdbapiName struct {

	// Alternative names for the person, which may include stage names,
	// nicknames, or other variations.
	AlternativeNames []string `json:"alternativeNames"`

	// A brief biography or description of the person, which may include
	// their career highlights, achievements, and other relevant information.
	Biography string `json:"biography,omitempty"`

	// The birth date of the person, represented as a Date message.
	BirthDate *ImdbapiPrecisionDate `json:"birthDate,omitempty"`

	// The birth location of the person, which may include the city and country of birth.
	BirthLocation string `json:"birthLocation,omitempty"`

	// The birth name of the person, which may differ from their display name.
	BirthName string `json:"birthName,omitempty"`

	// The death date of the person, represented as a Date message.
	// This field may be empty if the person is still alive.
	DeathDate *ImdbapiPrecisionDate `json:"deathDate,omitempty"`

	// The death location of the person, which may include the city and country of death.
	DeathLocation string `json:"deathLocation,omitempty"`

	// The reason for the person's death, if applicable.
	DeathReason string `json:"deathReason,omitempty"`

	// The display name of the person, typically their full name.
	DisplayName string `json:"displayName,omitempty"`

	// The height of the person in centimeters.
	HeightCm int32 `json:"heightCm,omitempty"`

	// The unique identifier for the name in the IMDb database.
	ID string `json:"id,omitempty"`

	// The IMDb popularity meter ranking for the person, which includes
	// their current rank, change direction, and difference from the previous measurement.
	// This field is optional and may not be present for all names.
	MeterRanking *ImdbapiNameMeterRanking `json:"meterRanking,omitempty"`

	// The primary image associated with the person, such as a profile picture.
	PrimaryImage *ImdbapiImage `json:"primaryImage,omitempty"`

	// A list of primary professions associated with the person,
	// such as "Actor", "Director", "Producer", etc.
	PrimaryProfessions []string `json:"primaryProfessions"`
}

// Validate validates this imdbapi name
func (m *ImdbapiName) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBirthDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeathDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMeterRanking(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrimaryImage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiName) validateBirthDate(formats strfmt.Registry) error {
	if swag.IsZero(m.BirthDate) { // not required
		return nil
	}

	if m.BirthDate != nil {
		if err := m.BirthDate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("birthDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("birthDate")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiName) validateDeathDate(formats strfmt.Registry) error {
	if swag.IsZero(m.DeathDate) { // not required
		return nil
	}

	if m.DeathDate != nil {
		if err := m.DeathDate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deathDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deathDate")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiName) validateMeterRanking(formats strfmt.Registry) error {
	if swag.IsZero(m.MeterRanking) { // not required
		return nil
	}

	if m.MeterRanking != nil {
		if err := m.MeterRanking.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("meterRanking")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("meterRanking")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiName) validatePrimaryImage(formats strfmt.Registry) error {
	if swag.IsZero(m.PrimaryImage) { // not required
		return nil
	}

	if m.PrimaryImage != nil {
		if err := m.PrimaryImage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this imdbapi name based on the context it is used
func (m *ImdbapiName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBirthDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDeathDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMeterRanking(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePrimaryImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiName) contextValidateBirthDate(ctx context.Context, formats strfmt.Registry) error {

	if m.BirthDate != nil {

		if swag.IsZero(m.BirthDate) { // not required
			return nil
		}

		if err := m.BirthDate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("birthDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("birthDate")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiName) contextValidateDeathDate(ctx context.Context, formats strfmt.Registry) error {

	if m.DeathDate != nil {

		if swag.IsZero(m.DeathDate) { // not required
			return nil
		}

		if err := m.DeathDate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deathDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deathDate")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiName) contextValidateMeterRanking(ctx context.Context, formats strfmt.Registry) error {

	if m.MeterRanking != nil {

		if swag.IsZero(m.MeterRanking) { // not required
			return nil
		}

		if err := m.MeterRanking.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("meterRanking")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("meterRanking")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiName) contextValidatePrimaryImage(ctx context.Context, formats strfmt.Registry) error {

	if m.PrimaryImage != nil {

		if swag.IsZero(m.PrimaryImage) { // not required
			return nil
		}

		if err := m.PrimaryImage.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("primaryImage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("primaryImage")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiName) UnmarshalBinary(b []byte) error {
	var res ImdbapiName
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
