// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiImage The Image message represents an image associated with a person or title in the IMDb database.
//
// swagger:model imdbapiImage
type ImdbapiImage struct {

	// The height of the image in pixels.
	Height int32 `json:"height,omitempty"`

	// The type of the image, such as "poster", "still_frame", "event", etc.
	Type string `json:"type,omitempty"`

	// The URL of the image, which can be used to access the image file.
	URL string `json:"url,omitempty"`

	// The width of the image in pixels.
	Width int32 `json:"width,omitempty"`
}

// Validate validates this imdbapi image
func (m *ImdbapiImage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi image based on context it is used
func (m *ImdbapiImage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiImage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiImage) UnmarshalBinary(b []byte) error {
	var res ImdbapiImage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
