// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ImdbapiSortOrder  - ASC: Sort in ascending order.
//   - DESC: Sort in descending order.
//
// swagger:model imdbapiSortOrder
type ImdbapiSortOrder string

func NewImdbapiSortOrder(value ImdbapiSortOrder) *ImdbapiSortOrder {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ImdbapiSortOrder.
func (m ImdbapiSortOrder) Pointer() *ImdbapiSortOrder {
	return &m
}

const (

	// ImdbapiSortOrderASC captures enum value "ASC"
	ImdbapiSortOrderASC ImdbapiSortOrder = "ASC"

	// ImdbapiSortOrderDESC captures enum value "DESC"
	ImdbapiSortOrderDESC ImdbapiSortOrder = "DESC"
)

// for schema
var imdbapiSortOrderEnum []interface{}

func init() {
	var res []ImdbapiSortOrder
	if err := json.Unmarshal([]byte(`["ASC","DESC"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		imdbapiSortOrderEnum = append(imdbapiSortOrderEnum, v)
	}
}

func (m ImdbapiSortOrder) validateImdbapiSortOrderEnum(path, location string, value ImdbapiSortOrder) error {
	if err := validate.EnumCase(path, location, value, imdbapiSortOrderEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this imdbapi sort order
func (m ImdbapiSortOrder) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateImdbapiSortOrderEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this imdbapi sort order based on context it is used
func (m ImdbapiSortOrder) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
