// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiNameMeterRanking The NameMeterRanking message represents the IMDb popularity meter ranking
// for a person, including their current rank, change direction, and difference
// from the previous measurement.
// This ranking is used to indicate the popularity of the person over time.
//
// swagger:model imdbapiNameMeterRanking
type ImdbapiNameMeterRanking struct {

	// The direction of the change in rank, which can be "UP", "DOWN", or "none".
	ChangeDirection string `json:"changeDirection,omitempty"`

	// The current rank of the person in the IMDb popularity meter.
	CurrentRank int32 `json:"currentRank,omitempty"`

	// The difference in rank compared to the previous measurement.
	// Positive for an increase, negative for a decrease, and zero for no change.
	Difference int32 `json:"difference,omitempty"`
}

// Validate validates this imdbapi name meter ranking
func (m *ImdbapiNameMeterRanking) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi name meter ranking based on context it is used
func (m *ImdbapiNameMeterRanking) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiNameMeterRanking) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiNameMeterRanking) UnmarshalBinary(b []byte) error {
	var res ImdbapiNameMeterRanking
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
