// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiYearsInvolved imdbapi years involved
//
// swagger:model imdbapiYearsInvolved
type ImdbapiYearsInvolved struct {

	// End year of involvement
	EndYear int32 `json:"endYear,omitempty"`

	// Start year of involvement
	StartYear int32 `json:"startYear,omitempty"`
}

// Validate validates this imdbapi years involved
func (m *ImdbapiYearsInvolved) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi years involved based on context it is used
func (m *ImdbapiYearsInvolved) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiYearsInvolved) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiYearsInvolved) UnmarshalBinary(b []byte) error {
	var res ImdbapiYearsInvolved
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
