// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiRating The Rating message represents the aggregate rating and votes count for a title.
//
// swagger:model imdbapiRating
type ImdbapiRating struct {

	// The aggregate_rating field contains the average rating of the title,
	// typically on a scale from 1 to 10.
	AggregateRating float32 `json:"aggregateRating,omitempty"`

	// The votes_count field contains the total number of votes cast for the title.
	VoteCount int32 `json:"voteCount,omitempty"`
}

// Validate validates this imdbapi rating
func (m *ImdbapiRating) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this imdbapi rating based on context it is used
func (m *ImdbapiRating) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiRating) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiRating) UnmarshalBinary(b []byte) error {
	var res ImdbapiRating
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
