// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImdbapiAwardNomination AwardNomination represents a nomination for an award.
//
// The unique identifier for the award nomination.
//
//	string id = 1  [(google.api.field_visibility).restriction = "INTERNAL"];
//
// swagger:model imdbapiAwardNomination
type ImdbapiAwardNomination struct {

	// The category of the award nomination.
	Category string `json:"category,omitempty"`

	// The event associated with the award nomination.
	Event *ImdbapiEvent `json:"event,omitempty"`

	// Whether the nomination is a winner.
	IsWinner bool `json:"isWinner,omitempty"`

	// The nominees associated with the award nomination.
	Nominees []*ImdbapiName `json:"nominees"`

	// The text description of the award nomination.
	Text string `json:"text,omitempty"`

	// The titles associated with the award nomination.
	Titles []*ImdbapiTitle `json:"titles"`

	// The rank of the winner in the nomination.
	WinnerRank int32 `json:"winnerRank,omitempty"`

	// The year of the award nomination.
	Year int32 `json:"year,omitempty"`
}

// Validate validates this imdbapi award nomination
func (m *ImdbapiAwardNomination) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEvent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNominees(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiAwardNomination) validateEvent(formats strfmt.Registry) error {
	if swag.IsZero(m.Event) { // not required
		return nil
	}

	if m.Event != nil {
		if err := m.Event.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("event")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("event")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiAwardNomination) validateNominees(formats strfmt.Registry) error {
	if swag.IsZero(m.Nominees) { // not required
		return nil
	}

	for i := 0; i < len(m.Nominees); i++ {
		if swag.IsZero(m.Nominees[i]) { // not required
			continue
		}

		if m.Nominees[i] != nil {
			if err := m.Nominees[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nominees" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("nominees" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiAwardNomination) validateTitles(formats strfmt.Registry) error {
	if swag.IsZero(m.Titles) { // not required
		return nil
	}

	for i := 0; i < len(m.Titles); i++ {
		if swag.IsZero(m.Titles[i]) { // not required
			continue
		}

		if m.Titles[i] != nil {
			if err := m.Titles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("titles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("titles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this imdbapi award nomination based on the context it is used
func (m *ImdbapiAwardNomination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEvent(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNominees(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTitles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImdbapiAwardNomination) contextValidateEvent(ctx context.Context, formats strfmt.Registry) error {

	if m.Event != nil {

		if swag.IsZero(m.Event) { // not required
			return nil
		}

		if err := m.Event.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("event")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("event")
			}
			return err
		}
	}

	return nil
}

func (m *ImdbapiAwardNomination) contextValidateNominees(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Nominees); i++ {

		if m.Nominees[i] != nil {

			if swag.IsZero(m.Nominees[i]) { // not required
				return nil
			}

			if err := m.Nominees[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nominees" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("nominees" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ImdbapiAwardNomination) contextValidateTitles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Titles); i++ {

		if m.Titles[i] != nil {

			if swag.IsZero(m.Titles[i]) { // not required
				return nil
			}

			if err := m.Titles[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("titles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("titles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImdbapiAwardNomination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImdbapiAwardNomination) UnmarshalBinary(b []byte) error {
	var res ImdbapiAwardNomination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
